---
- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt: 
      update_cache: yes

  - name: install pip3 package
    apt:
      name: python3-pip
      
  - name: install python3 package
    apt:
      name: python3
      
  - name: install mariadb package
    apt:
      name: mariadb-server
  
  - name: instal java open-jdk
    apt:
      name: default-jdk
